### ISSUE TITLE
tag incompatibilities on about.xml

### ISSUE THREAD

**Issue by Lobz** [MoogieOuttaMyDepth/RimworldMods#1]
I noticed Interbreeding and Wild Breeding are incompatible when I loaded them and got a lot of errors.
Please add incompatibility in your About.xml in both mods. From the developing guide:

> - <incompatibleWith> (list, optional)
>   A list of mod packageIds that cannot be active at the same time as your mod. They still can be installed, but not active.
> 
>   Example:
> ```
>     <incompatibleWith>
>       <li>Ludeon.Rimworld.Royalty</li>
>       <li>ModderName.ModSeries.ModName</li>
>     </incompatibleWith>
> ```

**Comment by MoogieOuttaMyDepth** [comment]
Thanks for the report! Will fix that right now.
